name       : perl-business-ismn
version    : '1.203'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISMN-1.203.tar.gz : 4f53aedab2e687d4e1f72856eafc22159390621123daaf79e4506a897e293e88
license    : Artistic-2.0
component  : programming.perl
homepage   : https://metacpan.org/pod/Business::ISMN
summary    : Business::ISMN - work with International Standard Music Numbers
description: |
    Business::ISMN - work with International Standard Music Numbers
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
    - perl-tie-cycle
rundeps    :
    - perl-tie-cycle
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
