name       : perl-business-ismn
version    : '1.132'
release    : 6
source     :
    - https://github.com/briandfoy/business-ismn/archive/release-1.132.tar.gz : d20b8375cf1919bf4b21f82e5543bf35025775901137f9eceb1ccc3899f944af
license    : Artistic-2.0
component  : programming.perl
homepage   : https://github.com/briandfoy/business-ismn
summary    : Business::ISMN - work with International Standard Music Numbers
description: |
    Business::ISMN - work with International Standard Music Numbers
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
    - perl-tie-cycle
rundeps    :
    - perl-tie-cycle
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
