name       : perl-business-ismn
version    : 1.131
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISMN-1.131.tar.gz : 8fa479a0c6a846dd3aed86811d57266f07270a0d3abff333188976c2483fccf7
license    : Artistic-2.0
component  : programming.perl
summary    : Business::ISMN - work with International Standard Music Numbers
description: |
    Business::ISMN - work with International Standard Music Numbers
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
